# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.3
loader_version=0.18.4

# Mod Properties
mod_version=1.0.0
maven_group=us.potatoboy
archives_base_name=skywars

# Dependencies
# check these on https://modmuss50.me/fabric.html
fabric_version=0.140.2+1.21.11

# check this on https://ci.gegy.dev/job/plasmid/
plasmid_version=0.6.7-SNAPSHOT+1.21.11